DROP DATABASE IF EXISTS aula07;
CREATE DATABASE aula07;
USE aula07;
CREATE TABLE cliente (
id MEDIUMINT(8) UNSIGNED AUTO_INCREMENT,
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) DEFAULT NULL,
cidade VARCHAR(255),
PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1;

INSERT INTO cliente (nome,email,cidade)
VALUES 
('Cynthia Clayton','nisl.sem@yahoo.ca','Okene'),
('Rebekah Carter','nunc@hotmail.edu','Forgaria nel Friuli'),
('Roth Mayer','id@protonmail.net','Horsham'),
('Miriam Roman','quisque@icloud.org','Culiacán'),
('Rogan Green','fringilla.ornare@google.net','Cuenca'),
('Drew Sandoval','purus.gravida.sagittis@hotmail.edu','Yopal'),
('Maris Holland','metus.sit.amet@icloud.ca','Palanzano'),
('Benedict Barlow','duis@yahoo.net','Tierra Amarilla'),
('Yeo Mclaughlin','sollicitudin.adipiscing.ligula@outlook.ca','Diamer'),
('Harding Murray','pellentesque@outlook.ca','Bastia'),
('Tad Fitzpatrick','mus.proin.vel@aol.net','Tehuacán'),
('Reed Gillespie','nulla.eget.metus@protonmail.net','Seogwipo'),
('McKenzie Marshall','vehicula.risus@protonmail.edu','Kırıkhan'),
('Brandon Drake','sed.hendrerit@hotmail.couk','Almere'),
('Ariana Stein','sit.amet@yahoo.ca','Hospet'),
('Julie Reese','aliquet.libero@protonmail.couk','Floridablanca'),
('Jolie Gardner','arcu.vel@google.couk','Hidalgo del Parral'),
('Eric Melton','porttitor.scelerisque.neque@icloud.org','Cabo de Santo Agostinho'),
('Armando Griffin','natoque.penatibus@outlook.edu','Kinross'),
('Byron Alvarez','pulvinar.arcu@aol.ca','Việt Trì'),
('Josiah Christian','non.leo.vivamus@protonmail.couk','Pervomaisk'),
('Nigel Mcpherson','interdum.nunc.sollicitudin@icloud.couk','Hamar'),
('Renee Wallace','est.vitae.sodales@protonmail.edu','Cartagena'),
('Nichole Valentine','cursus.et@yahoo.ca','Mora'),
('Emma Bray','dolor.quisque.tincidunt@protonmail.com','Ludvika'),
('Madeline Rivers','aliquam.gravida@aol.ca','Blankenfelde-Mahlow'),
('Garth Huber','sed.facilisis.vitae@aol.com','Jeonju'),
('Wing Hester','proin@yahoo.net','Banbury'),
('Peter Terrell','in.faucibus.orci@google.edu','Gwangmyeong'),
('Tanner Lee','tristique.senectus@icloud.org','İskenderun'),
('Brenden Abbott','et.netus@yahoo.org','Siquirres'),
('Lani Henderson','nec.cursus.a@google.net','Belfast'),
('Moses Powers','malesuada.ut.sem@icloud.ca','Guadalupe'),
('Xander Stevenson','egestas.sed@google.com','Vernon'),
('Simon Parsons','tristique.pellentesque@aol.com','Saint-Nazaire'),
('Laurel Atkinson','purus.in@icloud.ca','Puerto Asís'),
('Azalia Bass','proin@icloud.com','Agartala'),
('Amaya Estes','nibh.aliquam@outlook.org','Mezzana'),
('Ralph Kennedy','fringilla@protonmail.edu','Lozova'),
('Stephanie Collins','placerat@outlook.net','Moscow'),
('Griffin Burris','tortor.nunc.commodo@outlook.org','Rio de Janeiro'),
('Vivien Willis','morbi.tristique@icloud.net','Pagadian'),
('Damian Short','suspendisse.sed.dolor@aol.net','Noisy-le-Grand'),
('Branden Sharp','dolor@protonmail.com','Cisnes'),
('Yasir Haynes','semper.tellus.id@google.net','Uzhhorod'),
('Brennan Ramsey','risus.donec@outlook.net','Białystok'),
('Stephanie Hardin','eu.dui.cum@yahoo.edu','Talisay'),
('Dante Perry','etiam@protonmail.net','Khyber Agency'),
('Ava Riddle','sed.pede@protonmail.edu','Potchefstroom'),
('Hamilton Diaz','pellentesque.massa@google.couk','Sète');

